Set UID instead of username (#220)
Fixes the following which occurs in MCOA on non-ocp clusters.
```
CreateContainerConfigError: “container has runAsNonRoot and image has non-numeric user (nobody),  cannot verify user is non-root”
```

Signed-off-by: Jacob Baungard Hansen <jacobbaungard@redhat.com>
Co-authored-by: Jacob Baungard Hansen <jacobbaungard@redhat.com>